spring:
  application:
    name: bikestore-back
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


bikestore:
  app:
    jwtSecret: mysecretthatshouldbelargenoeughtobesecure123456789
    jwtExpirationMs: 1000000